[project]
name = "package1"
version = "0.0.1"
description = "Application for serving user's orders"
authors = [
    {name = "Aleks",email = "sashakasyanova54@gmail.com"}
]
license = "MIT"
requires-python = "^3.12"
dependencies = [
    "fastapi (>=0.136.1,<0.137.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
